spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
coordinate:
  path:
    - [55.6725084, 52.4427404]
    - [55.7377197, 52.4063506]
yandex:
  url: https://taxi.yandex.ru/3.0/routestats
  skip_estimated_waiting: true
  supports_forced_surge: false