spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
yandex-request:
#  url: https://taxi.yandex.ru/3.0/routestats
#  url: http://ptsv2.com/t/47qx7-1659015937/post
  url: http://localhost:8080
  route: [[55.6725084, 52.4427404],[55.7377197, 52.4063506]]
  skip-estimated-waiting: true
  supports-forced-surge: false

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true