spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
coordinate:
  start-longitude: 55.6725084
  start-latitude: 52.4427404
  finish-longitude: 55.7377197
  finish-latitude: 52.4063506
yandex:
  url: https://taxi-routeinfo.taxi.yandex.net/taxi_info
  clid: ${YANDEX_CLID}
  apikey: ${YANDEX_APIKEY}